// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Methods;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260310185913_UpdateTables_UpdateDb")]
    partial class UpdateTables_UpdateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.DataBase.AddressesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("House")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("City", "Region", "Street", "House")
                        .IsUnique()
                        .HasDatabaseName("IX_Addresses_FullAddress")
                        .HasFilter("[House] IS NOT NULL");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.CarBrandsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_CarBrands_Name");

                    b.ToTable("CarBrands");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.CarModelsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarBrands_Id")
                        .HasColumnType("int")
                        .HasColumnName("CarBrands_Id");

                    b.Property<int?>("CarModifications_Id")
                        .HasColumnType("int")
                        .HasColumnName("CarModifications_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CarBrands_Id");

                    b.HasIndex("CarModifications_Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_CarModels_Name");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.CarModificationsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Drive")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("EngineSize")
                        .HasColumnType("float");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("YearEnd")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("YearStart")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Engine", "EngineSize", "Transmission", "Drive", "Body", "YearStart", "YearEnd")
                        .HasDatabaseName("IX_CarModifications_FullModification");

                    b.ToTable("CarModifications");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.CategoriesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.ManufacturersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Manufacturers_Name");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.OrderItemsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Orders_Id")
                        .HasColumnType("int")
                        .HasColumnName("Orders_Id");

                    b.Property<decimal>("PriceAtMoment")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("Products_Id")
                        .HasColumnType("int")
                        .HasColumnName("Products_Id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Orders_Id");

                    b.HasIndex("PriceAtMoment")
                        .HasDatabaseName("IX_OrderItems_PriceAtMoment");

                    b.HasIndex("Products_Id");

                    b.HasIndex("Quantity")
                        .HasDatabaseName("IX_OrderItems_Quantity");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.OrdersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("Users_Id")
                        .HasColumnType("int")
                        .HasColumnName("Users_Id");

                    b.HasKey("Id");

                    b.HasIndex("OrderDate")
                        .HasDatabaseName("IX_Orders_OrderDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Orders_Status");

                    b.HasIndex("Users_Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.ProductCarApplicabilityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarModifications_Id")
                        .HasColumnType("int")
                        .HasColumnName("CarModifications_Id");

                    b.Property<int?>("Products_Id")
                        .HasColumnType("int")
                        .HasColumnName("Products_Id");

                    b.HasKey("Id");

                    b.HasIndex("CarModifications_Id");

                    b.HasIndex("Products_Id");

                    b.ToTable("ProductCarApplicability");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.ProductsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Categories_Id")
                        .HasColumnType("int")
                        .HasColumnName("Categories_Id");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("Manufacturers_Id")
                        .HasColumnType("int")
                        .HasColumnName("Manufacturers_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("Categories_Id");

                    b.HasIndex("Manufacturers_Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name");

                    b.HasIndex("PartNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_PartNumber");

                    b.HasIndex("Price")
                        .HasDatabaseName("IX_Products_Price");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.StocksModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Products_Id")
                        .HasColumnType("int")
                        .HasColumnName("Products_Id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Warehouses_Id")
                        .HasColumnType("int")
                        .HasColumnName("Warehouses_Id");

                    b.HasKey("Id");

                    b.HasIndex("Products_Id");

                    b.HasIndex("Quantity")
                        .HasDatabaseName("IX_Stocks_Qantity");

                    b.HasIndex("Warehouses_Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.UsersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SurName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Clients_Email");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("IX_Clients_Login");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Clients_PhoneNumber");

                    b.HasIndex("SecondName", "FirstName", "SurName")
                        .HasDatabaseName("IX_Clients_FullName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.WarehousesAddressesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Addresses_Id")
                        .HasColumnType("int")
                        .HasColumnName("Addresses_Id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("Warehouses_Id")
                        .HasColumnType("int")
                        .HasColumnName("Warehouses_Id");

                    b.HasKey("Id");

                    b.HasIndex("Addresses_Id");

                    b.HasIndex("Warehouses_Id");

                    b.ToTable("WarehousesAddresses");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.WarehousesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Warehouses_IsActive");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Warehouses_Type");

                    b.HasIndex("Code", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Warehouses_CodeName");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.CarModelsModel", b =>
                {
                    b.HasOne("WebApi.Models.DataBase.CarBrandsModel", "CarBrands")
                        .WithMany("CarModels")
                        .HasForeignKey("CarBrands_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.DataBase.CarModificationsModel", "CarModifications")
                        .WithMany("CarModels")
                        .HasForeignKey("CarModifications_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CarBrands");

                    b.Navigation("CarModifications");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.OrderItemsModel", b =>
                {
                    b.HasOne("WebApi.Models.DataBase.OrdersModel", "Orders")
                        .WithMany("OrderItems")
                        .HasForeignKey("Orders_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.DataBase.ProductsModel", "Products")
                        .WithMany("OrderItems")
                        .HasForeignKey("Products_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.OrdersModel", b =>
                {
                    b.HasOne("WebApi.Models.DataBase.UsersModel", "Users")
                        .WithMany("Orders")
                        .HasForeignKey("Users_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.ProductCarApplicabilityModel", b =>
                {
                    b.HasOne("WebApi.Models.DataBase.CarModificationsModel", "CarModifications")
                        .WithMany("ProductCarApplicability")
                        .HasForeignKey("CarModifications_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApi.Models.DataBase.ProductsModel", "Products")
                        .WithMany("ProductCarApplicability")
                        .HasForeignKey("Products_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CarModifications");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.ProductsModel", b =>
                {
                    b.HasOne("WebApi.Models.DataBase.CategoriesModel", "Categories")
                        .WithMany("Products")
                        .HasForeignKey("Categories_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApi.Models.DataBase.ManufacturersModel", "Manufacturers")
                        .WithMany("Products")
                        .HasForeignKey("Manufacturers_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categories");

                    b.Navigation("Manufacturers");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.StocksModel", b =>
                {
                    b.HasOne("WebApi.Models.DataBase.ProductsModel", "Products")
                        .WithMany("Stocks")
                        .HasForeignKey("Products_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApi.Models.DataBase.WarehousesModel", "Warehouses")
                        .WithMany("Stocks")
                        .HasForeignKey("Warehouses_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Products");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.WarehousesAddressesModel", b =>
                {
                    b.HasOne("WebApi.Models.DataBase.AddressesModel", "Addresses")
                        .WithMany("WarehousesAddresses")
                        .HasForeignKey("Addresses_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApi.Models.DataBase.WarehousesModel", "Warehouses")
                        .WithMany("WarehousesAddresses")
                        .HasForeignKey("Warehouses_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Addresses");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.AddressesModel", b =>
                {
                    b.Navigation("WarehousesAddresses");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.CarBrandsModel", b =>
                {
                    b.Navigation("CarModels");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.CarModificationsModel", b =>
                {
                    b.Navigation("CarModels");

                    b.Navigation("ProductCarApplicability");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.CategoriesModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.ManufacturersModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.OrdersModel", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.ProductsModel", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductCarApplicability");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.UsersModel", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebApi.Models.DataBase.WarehousesModel", b =>
                {
                    b.Navigation("Stocks");

                    b.Navigation("WarehousesAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
