INSERT INTO Manufacturers (Name)
VALUES (N'Bosch'),
       (N'Mann-Filter'),
       (N'Filtron'),
       (N'Valeo'),
       (N'Febi Bilstein'),
       (N'Lemforder'),
       (N'KYB'),
       (N'TRW'),
       (N'Continental'),
       (N'NGK'),
       (N'Denso'),
       (N'Brembo'),
       (N'Sachs'),
       (N'SKF'),
       (N'Gates'),
       (N'Dayco'),
       (N'Hella'),
       (N'Magneti Marelli'),
       (N'Textar'),
       (N'Zimmermann'),
       (N'Mobil'),
       (N'Philips'),
       (N'Mahle'),
       (N'Purflux'),
       (N'Knecht'),
       (N'Fram'),
       (N'Champion'),
       (N'Bilstein'),
       (N'Monroe'),
       (N'Kayaba'),
       (N'Contitech'),
       (N'Castrol'),
       (N'ShellHelix'),
       (N'LiquiMoly'),
       (N'Motul'),
       (N'Varta'),
       (N'Exide'),
       (N'Mutlu'),
       (N'Banner'),
       (N'Osram'),
       (N'Febi'),
       (N'Meyle');