INSERT INTO CarModels (Name, CarBrands_Id, CarModifications_Id)
VALUES ('Vesta', 1, 1),
       ('Vesta', 1, 2),
       ('Granta', 1, 3),
       ('Largus', 1, 4),
       ('XRAY', 1, 5),
       ('Camry', 2, 6),
       ('Corolla', 2, 7),
       ('RAV4', 2, 5),
       ('Solaris', 3, 8),
       ('Creta', 3, 5),
       ('Rio', 4, 8),
       ('Sportage', 4, 9),
       ('Logan', 5, 1),
       ('Duster', 5, 5),
       ('Qashqai', 6, 6),
       ('Polo', 7, 7),
       ('Octavia', 8, 7),
       ('Focus', 9, 7),
       ('Cruze', 10, 7),
       ('X5', 11, 10);