INSERT INTO Manufacturers (Name)
VALUES ('Bosch'),
       ('Mann-Filter'),
       ('Filtron'),
       ('Valeo'),
       ('Febi Bilstein'),
       ('Lemforder'),
       ('KYB'),
       ('TRW'),
       ('Continental'),
       ('NGK'),
       ('Denso'),
       ('Brembo'),
       ('Sachs'),
       ('SKF'),
       ('Gates'),
       ('Dayco'),
       ('Hella'),
       ('Magneti Marelli'),
       ('Textar'),
       ('Zimmermann');