INSERT INTO CarBrands (Name)
VALUES ('Lada'),
       ('Toyota'),
       ('Hyundai'),
       ('Kia'),
       ('Renault'),
       ('Nissan'),
       ('Volkswagen'),
       ('Skoda'),
       ('Ford'),
       ('Chevrolet'),
       ('BMW'),
       ('Mercedes-Benz'),
       ('Audi'),
       ('Mazda'),
       ('Mitsubishi'),
       ('Subaru'),
       ('Honda'),
       ('Suzuki'),
       ('Geely'),
       ('Chery');